[package]
name = "synchro_servo"
version = "0.1.0"
authors = ["Paul Rouget <me@paulrouget.com>"]

[dependencies]
libservo = { git = "https://github.com/servo/servo.git", rev = "9c9bd17871" }
gleam = "0.4"
log = "0.3"
